### ISSUE TITLE
不会自动登陆游戏

### ISSUE THREAD

**Issue by 1634222787** [overflow65537/MAA_Punish#4]
![image](https://github.com/user-attachments/assets/7a2de813-f3ec-42dc-a658-324fa309ccbf)

MAA设置如上
![image](https://github.com/user-attachments/assets/f99f0237-0f81-4d34-adf2-b10a3ff3339b)
一直停留在登陆界面
mumu版本
![image](https://github.com/user-attachments/assets/1a0d2ca6-0314-4934-91b6-39b114ac1266)

**Comment by 1634222787** [comment]
![image](https://github.com/user-attachments/assets/bfbe89a7-d47f-4c9f-870d-0d06b0448e52)
mumu版本号

**Comment by overflow65537** [comment]
是开启后台保活了吗？
没开的话传一份log上来看看
```./debug/maa.log```

**Comment by 1634222787** [comment]
检查了一下，模拟器自动开启了后台保活，关闭之后恢复正常
